JobFinder/auth.py
from flask import Flask, render_template, request, url_for, session, redirect, flash, current_app, Response
#from flask_session import Session
from flask import Blueprint
from werkzeug.utils import secure_filename, send_from_directory
from JobFinder.helpers import get_db_conn, is_logged_in, send_dfa_token, allowed_file, validate_email, is_valid_password
import os



auth = Blueprint('auth', __name__)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        
        fname = request.form['fname']
        lname = request.form['lname']
        email = request.form['email']
        password = request.form['password']
        resume = request.files['resume']
        transcript = request.files['transcript']

        # check to see if account exists with email
        conn = get_db_conn()
        r = conn.execute(
            f"""SELECT email FROM user WHERE email = '{email}';"""
        ).fetchall()
        if len(r) > 0:
            flash('An account already exists with this email!', category='error')
            return render_template('register.html')

        # check for valid input
        if fname and lname and password:
            if validate_email(email):             

                path_to_r_file = None
                path_to_t_file = None

                if resume and transcript:
                    if allowed_file(resume.filename) and allowed_file(transcript.filename):
                        r_filename = secure_filename(resume.filename)
                        t_filename = secure_filename(transcript.filename)

                        resume.save(os.path.join(current_app.config['UPLOAD_FOLDER'], r_filename))
                        transcript.save(os.path.join(current_app.config['UPLOAD_FOLDER'], t_filename))
                        path_to_r_file = current_app.config['UPLOAD_FOLDER'] + r_filename
                        path_to_t_file = current_app.config['UPLOAD_FOLDER'] + t_filename

                    elif allowed_file(resume.filename):
                        flash('Invalid Transcript', category='error')
                        return render_template('register.html')
                    elif allowed_file(transcript.filename):
                        flash('Invalid Resume', category='error')
                        return render_template('register.html')

                elif resume:
                    if allowed_file(resume.filename):
                        r_filename = secure_filename(resume.filename)
                        resume.save(os.path.join(current_app.config['UPLOAD_FOLDER'], r_filename))
                        path_to_r_file = current_app.config['UPLOAD_FOLDER'] + r_filename
                    else:            
                        flash('Invalid Resume!', category='error')
                        return render_template('register.html')

                elif transcript:
                    if allowed_file(transcript.filename):
                        t_filename = secure_filename(transcript.filename)
                        transcript.save(os.path.join(current_app.config['UPLOAD_FOLDER'], t_filename))
                        path_to_t_file = current_app.config['UPLOAD_FOLDER'] + t_filename
                    else:
                        flash('Invalid Transcript!', category='error')
                        return render_template('register.html')
                else:
                    pass

                conn = get_db_conn()
                conn.execute(
                    f"""INSERT INTO user (first_n, last_n, email, password, permission_level, path_to_r_file, path_to_t_file) VALUES ('{fname}', '{lname}', '{email}', '{password}', 1, '{path_to_r_file}', '{path_to_t_file}');"""
                    )
                conn.commit()
                conn.close()
                return render_template('login.html')

            else: 
                flash('Invalid Email', category='error')
                return render_template('register.html')
        else: 
            flash('Please enter a First name, Last name, and password ', category='error')
            return render_template('register.html')


    return render_template('register.html')

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password'] #encrypted password

        # query database to verify user
        conn = get_db_conn()
        result = conn.execute(
            f"""SELECT * FROM user 
            WHERE email='{email}' AND password='{password}'"""
        ).fetchall()
        conn.close()

        if len(result) == 1:
            
            session['temp_email'] = email
            session['token'] = 'token' # TODO randomly generate this 

            send_dfa_token(email)
 
            flash(f'A DFA Token has been sent to {email}')
            return render_template('dfa.html')
        # start session

        else: # invalid credentials
            flash('Email and/or Password is invalid!', category='error')
            return render_template('login.html')

    # else, its a GET request
    return render_template('login.html')

@auth.route('/dfa', methods=['GET', 'POST'])
def dfa():

    if request.method == 'POST':
        token = request.form['token']

        if token == session['token']: # success
            
            conn = get_db_conn()
            result = conn.execute(f"""
            SELECT * from user WHERE email = '{session['temp_email']}';"""
            ).fetchall()[0]

            session['user_id'] = result['id']
            session['first_n'] = result['first_n']
            session['last_n'] = result['last_n']
            session['email'] = result['email']
            session['transcript'] = str(result['path_to_t_file']).split('\\')[-1] if result['path_to_t_file'] and len(result['path_to_t_file']) > 1 else 'None'
            session['resume'] = str(result['path_to_r_file']).split('\\')[-1] if result['path_to_r_file'] and len(result['path_to_r_file']) > 1 else 'None'
            session['perm_lvl'] = result['permission_level']
                

            return redirect(url_for('views.student_profile'))
        else:
            flash('Invalid Token!', category='error')
            return render_template('dfa.html')
    else:
        return render_template('dfa.html')
    
@auth.route('/logout', methods=['GET'])
def logout():
    for e in [e for e in session]:
        session.pop(e, None)
    return redirect(url_for('auth.login'))

@auth.route('/forgot_password', methods=['GET'])
def forgot_password():
    pass

@auth.route('/upload_transcript', methods=['POST'])
def upload_transcript():
    try:

        transcript = request.files['transcript']

        email = session['email']

        if transcript:
            if allowed_file(transcript.filename):
                t_filename = secure_filename(transcript.filename)

                # delete old file (if it exists)
                conn = get_db_conn()
                r = conn.execute(
                    f"""SELECT path_to_t_file FROM user WHERE email = '{email}';"""
                ).fetchall()
                old_filename = r[0]['path_to_t_file']
                if old_filename != 'None':
                    os.remove(os.path.join(current_app.config['UPLOAD_FOLDER'], old_filename))

                transcript.save(os.path.join(current_app.config['UPLOAD_FOLDER'], t_filename))
                path_to_t_file = current_app.config['UPLOAD_FOLDER'] + t_filename

                # set the path_to_t_file
                conn.execute(
                    f"""UPDATE user SET path_to_t_file = '{path_to_t_file}' WHERE email = '{email}'"""
                )
                conn.commit()
                conn.close()

                session['transcript'] = t_filename

                flash('Transcript was Successfully Uploaded!')
                return redirect(url_for('views.student_profile'))

            else:
                flash('Invalid Transcript!', category='error')
                return redirect(url_for('views.student_profile'))
        else:
            flash('Invalid Transcript!', category='error')
            return redirect(url_for('views.student_profile'))
    except Exception as ex:
        current_app.logger.error("Error occurred while uploading a transcript.", ex)
        flash('Error occurred while uploading transcript', category='error')
        return redirect(url_for('views.student_profile'))


@auth.route('/upload_resume', methods=['POST'])
def upload_resume():
    try:

        resume = request.files['resume']

        email = session['email']

        if resume:
            if allowed_file(resume.filename):
                r_filename = secure_filename(resume.filename)

                # delete old file (if it exists)
                conn = get_db_conn()
                r = conn.execute(
                    f"""SELECT path_to_r_file FROM user WHERE email = '{email}';"""
                ).fetchall()
                old_path = r[0]['path_to_r_file']

                if old_path:
                    os.remove(old_path)

                new_path = os.path.join(current_app.config['UPLOAD_FOLDER'], r_filename)

                resume.save(new_path)
                path_to_r_file = new_path

                # set the path_to_t_file
                conn.execute(
                    f"""UPDATE user SET path_to_r_file = '{path_to_r_file}' WHERE email = '{email}'"""
                )
                conn.commit()
                conn.close()

                session['resume'] = r_filename

                flash('Resume was Successfully Uploaded!')
                return redirect(url_for('views.student_profile'))

            else:
                flash('Invalid Resume!', category='error')
                return redirect(url_for('views.student_profile'))
        else:
            flash('Invalid Resume!', category='error')

JobFinder/views.py
from flask import Flask, render_template, request, url_for, session, redirect, flash, current_app, Response
import os
from flask import Blueprint
from .helpers import get_db_conn, is_logged_in, apply_for_job

views = Blueprint('views', __name__)


perm_lvls = {0: 'default', 1: 'student', 2: 'faculty'} # not in use

######################## VIEWS #####################################
@views.route('/')
def home():
    return render_template('home.html', session=session)

# job list view
@views.get('/jobs')
def job_finder():
    # get all jobs
    conn = get_db_conn()
    jobs = conn.execute(
        """SELECT job.id AS "job_id", job.title AS "job_title", job.date_listed, job.descrip AS "job_descrip", job.img_path, department.title AS "dept_title", user.first_n AS "first_n", user.last_n AS "last_n", job.dept_id AS 'dept_id' 
            FROM job 
            LEFT JOIN user ON job.user_id = user.id
            LEFT JOIN department ON job.dept_id = department.id;"""
    ).fetchall()

    if 'email' in session:
        jobsAppliedTo = conn.execute(f"""
            SELECT job_id FROM job_application WHERE user_id = {session['user_id']};
        """).fetchall()
        jobsAppliedTo = [job[0] for job in jobsAppliedTo]
    else: 
        jobsAppliedTo = ['']

    conn.close()

    return render_template('jobs.html', jobs=jobs, jobsAppliedTo=jobsAppliedTo, session=session)

@views.get('/jobs/<int:job_id>')
def get_job_info(job_id):

    conn = get_db_conn()
    job = conn.execute(
        f"""SELECT job.id AS "job_id", job.title AS "job_title", job.date_listed, job.descrip AS "job_descrip", job.img_path, department.title AS "dept_title", user.first_n AS "first_n", user.last_n AS "last_n" 
            FROM job 
            LEFT JOIN user ON job.user_id = user.id
            LEFT JOIN department ON job.dept_id = department.id
        WHERE job.id = {job_id};"""
    ).fetchall()[0]
    conn.close()

    if job != None:        
        return {
                'job_id': job['job_id'],
                'title': job['job_title'],
                'date_listed': job['date_listed'],
                'descrip': job['job_descrip'],
                'first_n': job['first_n'],
                'last_n': job['last_n'],
                'dept_title': job['dept_title']     
            } 


@views.route('/apply', methods=['POST'])
def apply():
    try:
        coverLetter = request.form['coverL']
        if 'transcript' in request.form:
            withTranscript = request.form['transcript']
        else:
            withTranscript = None

        if 'resume' in request.form:
            withResume = request.form['resume']
        else:
            withResume = None

        jobId = request.form['jobId']

        apply_for_job(jobId, withTranscript, withResume)

        flash("Successfully Applied!")
        return redirect(url_for('views.job_finder'))                                      
    except Exception as ex:
        current_app.logger.error(ex)
        flash("Failed to Apply", category='error')
        return redirect(url_for('views.job_finder'))
   

@views.route('/student_profile')
def student_profile():
    if 'email' in session:
        return render_template('profile.html', session=session)
    else:
       flash("Login/Register to create your profile!", category='info')
       return redirect(url_for('auth.login'))

@views.route('/departments')
def departments():
    pass

@views.route('/department_profile/<int:dept_id>')
def department_profile(dept_id):
    # get desired department
    conn = get_db_conn()
    jobs = conn.execute(
        f"""SELECT job.id AS id, job.title AS title, job.date_listed, job.descrip, job.img_path, user.first_n, user.last_n  
            FROM job 
            LEFT JOIN user ON job.user_id = user.id
            LEFT JOIN department ON job.dept_id = department.id
            WHERE department.id = {dept_id};"""
    ).fetchall()  

    if 'email' in session:
        jobsAppliedTo = conn.execute(f"""
            SELECT job_id FROM job_application WHERE user_id = {session['user_id']};
        """).fetchall()
        jobsAppliedTo = [job[0] for job in jobsAppliedTo]
    else: 
        jobsAppliedTo = ['']

    dept_info = conn.execute(
        f"""SELECT id, title, email, descrip, website_url FROM department WHERE department.id = {dept_id};"""
    ).fetchall()[0]

    conn.close()
    return render_template('department.html', jobs=jobs, jobsAppliedTo=jobsAppliedTo, dept_info=dept_info)


@views.route('/manage_jobs')
def manage_jobs():

    conn = get_db_conn()
    jobs = conn.execute(f"""
        SELECT * from job WHERE user_id = {session['user_id']};
    """).fetchall()

    return render_template('manage_jobs.html', session=session, jobs=jobs)

@views.route('/create_job', methods=['POST'])
def create_job():
    title = request.form.get('title', None)
    descrip = request.form.get('descrip', None)
    image = request.files.get('image', None)

    if title != None and descrip != None and image != None:

        img_path = os.path.join(current_app.config['IMAGE_FOLDER'], image.filename)
        image.save(img_path)

        conn = get_db_conn()
        conn.execute(f"""
            INSERT INTO job (title, descrip, img_path, user_id) VALUES ('{title}', '{descrip}', '{img_path}', {session['user_id']});
        """)
        conn.commit()
        conn.close()
    else: 
        flash("Error entering job", category='error')
        return redirect(url_for('views.manage_jobs'))
    
    return redirect(url_for('views.manage_jobs'))

@views.route('/delete_job', methods=['POST'])
def delete_job():

    job_id = request.form.get('name', None)

    conn = get_db_conn()
    conn.execute(f"""
        DELETE FROM job WHERE id = {job_id};
    """)
    conn.commit()
    conn.close()

    return Response(status=204)

JobFinder/templates/auth_base.html
<!doctype html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title></title>       
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    {% block style %}{% endblock %}
</head>
<body>
    <main role="main" class="container">           
      <div class="container-lg" style="height:57.78px">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            {% if category == 'error' %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% elif category == 'info' %}
              <div class="alert alert-info alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% else %}
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                </button>
              </div>
            {% endif %}
          {% endfor %}
        {% endif %}
      {% endwith %}
      </div>

      <div class="row">
          {% block content %}{% endblock %}
      </div>
    </main>
      <!--FOOTER-->
    <footer class="footer mt-auto text-center text-white" style="background-color: #3f51b5;">
      <!-- Grid container -->
      <div class="container">
        <!-- Section: Links -->
        <section class="mt-3">
          <!-- Grid row-->
          <div class="row text-center d-flex justify-content-center pt-4">
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href={{ url_for('views.home') }} class="text-white">Home</a>
              </h6>
            </div>
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href={{ url_for('views.job_finder') }} class="text-white">Jobs</a>
              </h6>
            </div>
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href={{ url_for('views.student_profile') }} class="text-white">Profile</a>
              </h6>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row-->
        </section>
        <!-- Section: Links -->
  
        <hr class="my-1" />
  
        <!-- Section: Text -->
        <section class="mb-5">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-8">
              <p>
                <br>University of Wisconsin-Eau Claire
                <br>105 Garfield Avenue | P.O. Box 4004 | Eau Claire, WI 54702-4004 | 715-836-4636
              </p>
            </div>
          </div>
        </section>
        <!-- Section: Text -->
  
      </div>
      <!-- Grid container -->
  
      
      <div
           class="text-center p-3"
           style="background-color: rgba(0, 0, 0, 0.2)"
           >
        
        <p class="text-white"
           >UWEC Student Job Finder</p>
      </div>
     
    </footer>
        <!-- Footer -->
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% block script %}{% endblock %}
</html>

JobFinder/templates/base.html
<!doctype html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title> Homepage </title>       
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="icon" href="../static/images/uweclogo.png" type="image/png">
    {% block style %}{% endblock %}
</head>
<body>
      <!-- header/navbar-->
      <nav class="navbar navbar-expand" style="background-color: #2b4083">
        <div class="container-md" style="justify-content: start;" >
            {# <p class="navbar-brand mt-1">
                <img class="d-inline-block align-center" src="../static/images/uwecwhite.webp" width="200px">
                Job Finder
            </p> #}
            <div>
            <img class="d-inline-block align-center" src="../static/images/uwecwhite.webp" width="200px">
            </div>
            <h3 class="text-white me-2">Job Finder</h3>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href={{ url_for('views.home') }} class="nav-link">Home</a>
                </li>
                <li class="nav-item mb-1">
                    <a href={{ url_for('views.job_finder') }} class="nav-link">Jobs</a>
                </li>
                <li class="nav-item mb-1">
                    <a href={{ url_for('views.student_profile') }} class="nav-link">Profile</a>
                </li>
                {% if session['perm_lvl'] == 2 %}
                  <li class="nav-item">
                    <a href={{ url_for('views.manage_jobs') }} class="nav-link">Manage Jobs</a>
                  </li>
                {% endif %}
                <span class="me-1"></span>
                {% if session['email'] %}
                  <li class="nav-item mt-1">
                    <a href={{ url_for('auth.logout') }} type="button" class="btn btn-primary" role="button">Logout</a>
                  </li>
                {% else %}
                  <li class="nav-item mt-1">
                    <a href={{ url_for('auth.login') }} type="button" class="btn btn-primary" role="button">Login</a>
                  </li>
                {% endif %}                  
            </ul>
        </div>
    </nav>

    <main role="main" class="container h-100" style="display:flex;flex-flow:column;flex: 0 1 auto;">           
      <div class="container-lg" style="height:57.78px">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            {% if category == 'error' %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% elif category == 'info' %}
              <div class="alert alert-info alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% else %}
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                </button>
              </div>
            {% endif %}
          {% endfor %}
        {% endif %}
      {% endwith %}
      </div>

      <div class="row">
          {% block content %}{% endblock %}
      </div>
    </main>
      <!--FOOTER-->
    <footer class="footer mt-auto text-center text-white" style="background-color: #3f51b5;">
      <!-- Grid container -->
      <div class="container">
        <!-- Section: Links -->
        <section class="mt-3">
          <!-- Grid row-->
          <div class="row text-center d-flex justify-content-center pt-4">
            <!-- Grid column -->
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href={{ url_for('views.home') }} class="text-white">Home</a>
              </h6>
            </div>
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href={{ url_for('views.job_finder') }} class="text-white">Jobs</a>
              </h6>
            </div>
            <div class="col-md-2">
              <h6 class="text-uppercase font-weight-bold">
                <a href={{ url_for('views.student_profile') }} class="text-white">Profile</a>
              </h6>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row-->
        </section>
        <!-- Section: Links -->
  
        <hr class="my-1" />
  
        <!-- Section: Text -->
        <section class="mb-5">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-8">
              <p>
                <br>University of Wisconsin-Eau Claire
                <br>105 Garfield Avenue | P.O. Box 4004 | Eau Claire, WI 54702-4004 | 715-836-4636
              </p>
            </div>
          </div>
        </section>
        <!-- Section: Text -->
  
      </div>
      <!-- Grid container -->
  
      
      <div
           class="text-center p-3"
           style="background-color: rgba(0, 0, 0, 0.2)"
           >
        
        <p class="text-white"
           >UWEC Student Job Finder</p>
      </div>
     
    </footer>
        <!-- Footer -->
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
{% block script %}{% endblock %}
</html>

JobFinder/templates/department.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <header class="row text-white py-3" style="background-color: #2b4083">
        <div class="col">
            <h1 class="" style="color:white;">{{ dept_info['title'] }}</h1>
        </div>
    </header>

    <main class="row mt-4">
        <div class="col-md-8">
            <h2>About</h2>
            <p>{{ dept_info['descrip'] }}</p>
        </div>

        <div class="col-md-4">
            <h2>Contact Information</h2>
            <p>Website: <a href={{ dept_info['website_url'] }}>{{ dept_info['website_url'] }}</a></p>
            <p>Email: <a href="mailto:{{ dept_info['email'] }}">{{ dept_info['email'] }}</a></p>
        </div>
    </main>

    <section class="row my-4">
        <div class="">
            <h2 class="text-center mb-3">Employment Openings</h2>
            {% if jobs %}
            {% for job in jobs %}
                {% set id = job['id']|string %}
                {% set descripID = "descrip" ~ id %}
                <div class="card m-1 w-75 mx-auto" style="min-height: 125px;max-width: 100%;">
                    <div class="row g-0 h-100">
                        <div class="col-md-3">
                            <img src={{ job['img_path'] }} class="img-fluid rounded-start" alt=""
                                style="height: 200px; width: 100%; object-fit: fill;"> <!-- Optional image-->
                        </div>
                        <div class="col-md-7">
                            <div class="card-body">
                                <h5 class="card-title fw-bold">{{ job['title'] }}</h5>
                                <p id="jobId" hidden>{{ id }}</p>
                                <p class="card-text">Posted by: {{ job['first_n'] ~ ' ' ~ job['last_n'] }}</p>   
                                <p class="card-text"><small class="text-body-secondary">Posted: {{ job['date_listed'].format() }}</small></p>
                            </div>
                        </div>
                        <div class="col-md-2 flex-column d-flex">
                            {% if job['id'] in jobsAppliedTo %}
                              <button class="btn btn-success mt-5 m-2">Applied!</button>
                            {% else %}
                              <button class="btn btn-primary apply mt-5 m-2" data-bs-toggle="modal" data-bs-target="#apply-modal">Apply</button>   <!-- Button trigger modal -->
                            {% endif %}
                            <button class="btn btn-secondary m-2" data-bs-toggle="collapse"
                                data-bs-target="#{{ descripID }}" aria-expanded="false">See More</button>
                        </div>
                        <div class="row">
                            <div class="collapse multi-collapse" id="{{ descripID }}">
                                <p class="card-text">{{ job['descrip'] }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% else %}
                <p>No jobs posted by this department.</p>
            {% endif %}


    </section>
</div>
{% endblock %}

JobFinder/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <!-- information -->
    <div class="container">              <!--12 column sizes in 1 row hard-coded, can choose with numbers OR auto-->
        <div class="row" id="row1">
            
        </div>
    </div>
{% endblock %}

JobFinder/templates/login.html
{% extends "auth_base.html" %}

{% block content %}
  <div class="container d-flex justify-content-center mb-5">
    <form action="./login" method="POST"  style="width: 500px; margin-right: 5px; margin-top: 40px; border: 2px solid rgb(162, 162, 162); padding: 40px; border-radius: 5px;">
      <div  style="text-align: center;">
        <h2 style="color: #3f51b5; margin-bottom: 15px;">LOGIN</h2>
        <h6 style="color: rgb(162, 162, 162);">Please enter your UWEC email and password </h6>
        <br>
      </div>

          <!-- Email input -->
           <div data-mdb-input-init class="form-outline mb-4" >
            <input type="email" id="form2Example1" name="email" class="form-control" placeholder=user1234@uwec.edu>
            <label class="form-label" for="form2Example1">Email address</label>
          </div>
        
          <!-- Password input -->
          <div data-mdb-input-init class="form-outline mb-4">
            <input type="password" id="form2Example2" name="password" class="form-control" placeholder="********"/>
            <label class="form-label" for="form2Example2">Password</label>
          </div>
        
          <!-- 2 column grid layout for inline styling -->
          <div class="row mb-4">
            <div class="col d-flex justify-content-center">
              <!-- Checkbox -->
              <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="form2Example31"/>
                <label class="form-check-label" for="form2Example31"> Remember me </label>
              </div>
            </div>
        
            <div class="col">
              <!-- Simple link -->
              <a href={{ url_for('auth.forgot_password') }}>Forgot password?</a>
            </div>
          </div>
        
          <!-- Submit button -->
          <div class = "text-center">
          <button type="submit" role="button" style="width: 200px;" data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Login</button>
          </div>
          <div class="text-center">
            <a href={{ url_for('auth.register') }}><p>Need an Account?</p></a>
          </div>
      
    </form>
  </div> 
{% endblock %}